(4-10)  add images
alfiya-udc/places pull request #9
Opened 2021-04-07 05:07 UTC by alfiya-udc

2021-04-07 17:52 UTC, artem-zaitsev requested changes
Необходимы правки

2021-04-07 17:52 UTC, artem-zaitsev commented on lib/ui/screen/SightCard.dart
> +                    child: CircularProgressIndicator(),
У Вас бесконечный лоадер. По заданию требовалось все таки показать лоадер, который привязан к прогрессу. Или по-другому: увеличивается пропорционально прогрессу.

2021-04-07 17:52 UTC, artem-zaitsev commented on lib/ui/screen/SightCard.dart
> +                  if (loadingProgress == null) return child;
Это не имеет смысла, если не ощибаюсь будет вызвано под капотом у виджета.

2021-04-08 05:02 UTC, alfiya-udc commented
![image](https://user-images.githubusercontent.com/33545574/113970950-7e58a680-9840-11eb-92d1-5d1a9ac61dc2.png)
![image](https://user-images.githubusercontent.com/33545574/113971080-bd86f780-9840-11eb-8a9b-656dce1fdadd.png)

2021-04-08 07:14 UTC, artem-zaitsev approved these changes

2021-04-08 16:58 UTC, merged